VIEWNIOR_DIR := $(HOME)/.config/viewnior

install-viewnior:
	ln -sfn $(CURDIR)/viewnior.conf $(VIEWNIOR_DIR)/viewnior.conf
	ln -sfn $(CURDIR)/accel_map $(VIEWNIOR_DIR)/accel_map

clean-viewnior:
	rm -f $(VIEWNIOR_DIR)/viewnior.conf
	rm -f $(VIEWNIOR_DIR)/accel_map